FROM python:3.11-slim

# Install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends i2c-tools build-essential && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY driver ./driver
COPY run.sh ./
RUN chmod +x run.sh

ENTRYPOINT [ "./run.sh" ]
